### ISSUE TITLE
Error Initializing submodules

### ISSUE THREAD

**Issue by edwinbosire** [Auntie-Player/apple-tv#1]
•••• This is not an open issue, more of a solution to a problem I encountered****

If you get Permission denied (publickey) or related errors while cloning submodules by running
git submodule update --init --recursive

Do the following from your root directory (<path-to-repo>/apple-tv/ )

'$open .git/config'

Change the last line from
url = git@github.com:3sidedcube/iOS-ThunderRequest.git

To

url = git://github.com/3sidedcube/iOS-ThunderRequest.git

This is the Read-Only URL (which is what you want)

**Comment by jiazufei** [comment]
![image](https://cloud.githubusercontent.com/assets/3351691/10684120/6505a978-797c-11e5-8baf-7e05d48f39a2.png)
