### ISSUE TITLE
Any chance of getting it to play HD stream?

### ISSUE THREAD

**Issue by zenjabba** [Auntie-Player/apple-tv#3]

**Comment by grgar** [comment]
The following code in AuntieController.m's `getStreamURLForVersion` obtains the highest bitrate stream. If a HD stream is available, it will be selected as the `bestQualityStreamString` by this code and be the one that is played.

``` obj-c
NSArray *mediaObjects = response.dictionary[@"media"];
NSString *bestQualityStreamString;
NSInteger topBitrate = 0;
for (NSDictionary *singleStream in mediaObjects) {
    if ([singleStream[@"bitrate"] integerValue] > topBitrate) {
        topBitrate = [singleStream[@"bitrate"] integerValue];
        NSArray *connectionObjects = singleStream[@"connection"];
        NSDictionary *streamObject = connectionObjects.firstObject;
        bestQualityStreamString = streamObject[@"href"];
    }
}
```

Thus, HD should already be supported. If you're not seeing HD, make sure that the content you are attempting to play is available in HD. You can set breakpoints around this code in Xcode and check that it is selecting the correct stream for the content that you are attempting to view.

**Comment by phillipcaudell** [comment]
@grgarside nailed it.
