### ISSUE TITLE
Not able to play videos on Apple TV or simulator

### ISSUE THREAD

**Issue by lumierephoto** [Auntie-Player/apple-tv#6]
I'm able to build the project successfully to Apple TV or simulator, but am unable to play any of the stations.

Is the BBC API blocked in the USA?

Here's the screen I get:

![1](https://cloud.githubusercontent.com/assets/981541/11129287/15e08782-8944-11e5-8507-7dfa8996e4c7.png)

This is an error I get, but not 100% sure it's related:

2015-11-12 13:43:32.892 Auntie Player[27033:1110160] [/BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreUI_Sim/CoreUI-370.8/Bom/Storage/BOMStorage.c:517] <memory> is not a BOMStorage file

**Comment by ghost** [comment]
Pretty sure BBC is restricted to the UK, i'm in the UK running Auntie Player without any problems.
Sorry dude :(

**Comment by moooooooo** [comment]
i'm in New Zealand but have a global DNS service which means i am anywhere
so the Auntie Player works for me.

**Comment by phillipcaudell** [comment]
BBC content restrictions block access to the API outside of the UK.
